### PR TITLE
Add checkstyle rule for TODO and FIXME comments

### PR DESCRIPTION
**Pull request by KevinHudemann**
BLI: https://github.com/SAP/cloud-sdk-java-backlog/issues/282

### CODE REVIEW

**Review by stippi2 — COMMENTED** [review]
From the old [Jenkinsfile](https://github.wdf.sap.corp/MA/sdk/blob/b0776cc8dbb0efe458ffe8d25629f36d10705eb2/Jenkinsfile#L723), I understand it was case insensitive. The [examples](https://checkstyle.sourceforge.io/checks/misc/todocomment.html#Example2-code) in checkstyle suggest the check would no longer be case-insensitve. Not sure if this was already discussed and deemed OK.

**Comment by KevinHudemann** [comment]
> From the old [Jenkinsfile](https://github.wdf.sap.corp/MA/sdk/blob/b0776cc8dbb0efe458ffe8d25629f36d10705eb2/Jenkinsfile#L723), I understand it was case insensitive. The [examples](https://checkstyle.sourceforge.io/checks/misc/todocomment.html#Example2-code) in checkstyle suggest the check would no longer be case-insensitve. Not sure if this was already discussed and deemed OK.

Yeah good point. No it was not discussed.
Maybe adding both in lower case would be sufficient.

**Comment by stippi2** [comment]
> Maybe adding both in lower case would be sufficient.

ChatGPT claims that regex like `(?i)` is not supported by this module and also suggests just listing (most common) permutations.

**Review by Johannes-Schneider — APPROVED** [review]
LGTM

**Pull request merged**
